# Generated by Django 6.0.2 on 2026-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0002_remove_book_category_alter_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
